Add checked_uint_to_bits, deprecate uint_to_bits
tari-project/tari_utilities pull request #9
Opened 2021-04-28 09:19 UTC by sdbondi

- Adds checked_uint_to_bits, that returns None if the bit_count > 32 or
  64 (depending on architecture). This prevents an overflow on the
  shift-left operation.
- Deprecates uint_to_bits.
- uint_to_bits panics if the bit_count is large in release mode
  (previously only debug)
- Added basic tests

Tari usage: this function was only used with bit_count 11

2021-04-28 13:18 UTC, delta1 approved these changes
LGTM

2021-05-13 11:32 UTC, delta1 requested changes
So looking at this again, I actually disagree with deprecating. This (and the inverse) are used in exactly one place each in the tari repo. I suggest that we just make the breaking change publish a new semver, and update the tari code.

What do you think @sdbondi and @mikethetike?

2021-05-13 11:39 UTC, sdbondi commented
@delta1 I don't have a strong opinion either way. Whoever is responsible for updating the tari_utilities crate will have to deal with the error and that will be an easy task so yeah, deprecating it just seems like an additional step.

2021-07-18 06:29 UTC, sdbondi commented
bump - I think this can be merged

2021-07-18 07:57 UTC, delta1 approved these changes

2021-07-18 14:40 UTC, CjS77 approved these changes

2021-07-18 14:40 UTC, merged